name = "grades-viewer"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist/client", binding = "ASSETS" }

# D1 binding — 学生成绩存这里
[[d1_databases]]
binding = "DB"
database_name = "grades-db"
database_id = "6f39b871-9c81-4c16-a6bb-c0e26394372b"

[vars]
PUBLIC_VERSION = "0.1"